trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'



steps:
  - task: Checkout@1
    displayName: 'Checkout Code'

  - script: |
      mkdir -p ~/.ssh
      echo "$SSH_KEY" > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts
    displayName: 'Prepare SSH Key'

    env:
      VM_USER: '$(AZURE_VM_USER)'
      VM_IP: '$(AZURE_VM_IP)'
      SSH_KEY: '$(AZURE_VM_SSH_KEY)'

  - script: |
      ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP << 'EOF'
        set -e
        cd /var/www/ecommerce-laptop
        git fetch origin main
        git reset --hard origin/main
        git pull origin main --rebase
        composer install --no-dev --optimize-autoloader
        php artisan config:cache
        php artisan queue:restart
        php artisan optimize
        php artisan migrate
        sudo systemctl restart nginx
      EOF
    displayName: 'Deploy via SSH'