trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: 'MyAzureVMServiceConnection'
      runOptions: 'commands'
      commands: |
        if [ ! -d /var/www/ecommerce-laptop/.git ]; then
          rm -rf /var/www/ecommerce-laptop
          git clone git@github.com:igonoralexander/ecommerce-laptop.git /var/www/ecommerce-laptop
        else
          cd /var/www/ecommerce-laptop
          git pull origin main
        fi

        cd /var/www/ecommerce-laptop
        composer install --no-dev --optimize-autoloader
        php artisan migrate
        php artisan config:cache
        php artisan queue:restart
        sudo systemctl restart nginx