trigger:
  branches:
    include:
      - main

pool:
  name: Default  # Uses your self-hosted agent

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: 'MyAzureVMServiceConnection'
      runOptions: 'commands'
      commands: |
        cd /var/www/ecommerce-laptop
        git pull origin main
        composer install --no-dev --optimize-autoloader
        php artisan migrate
        php artisan config:cache
        php artisan queue:restart
        sudo systemctl restart nginx