trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: 'MyAzureVMServiceConnection'
      runOptions: 'commands'
      commands: |
        cd /var/www/ecommerce-laptop

        [ ! -d /var/www/ecommerce-laptop/git ] || (cd /var/www/ecommerce-laptop && git remote set-url origin https://github.com/igonoralexander/ecommerce-laptop.git && git fetch origin main 2>&1 && git reset --hard origin/main 2>&1 && git pull origin main --rebase 2>&1 )

        composer install --no-dev --optimize-autoloader 2>&1 | grep -v 'Deprecation Notice' || true
        php artisan config:cache
        php artisan queue:restart
        php artisan optimize
        php artisan migrate --force
        sudo systemctl restart nginx