trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: 'MyAzureVMServiceConnection'
      runOptions: 'commands'
      commands: |
        [ ! -d /var/www/ecommerce-laptop/.git ] && rm -rf /var/www/ecommerce-laptop && git clone https://github.com/igonoralexander/ecommerce-laptop.git /var/www/ecommerce-laptop || (cd /var/www/ecommerce-laptop && git pull origin main)

        cd /var/www/ecommerce-laptop
        composer install --no-dev --optimize-autoloader
        php artisan migrate
        php artisan config:cache
        php artisan queue:restart
        sudo systemctl restart nginx
