trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:
  - checkout: self

  - task: SSH@0
    inputs:
      sshEndpoint: 'MyAzureVMServiceConnection'
      runOptions: 'commands'
      commands: |
        if [ ! -d /var/www/ecommerce-laptop/.git ]; then
          sudo rm -rf /var/www/ecommerce-laptop
          git clone https://github.com/igonoralexander/ecommerce-laptop.git /var/www/ecommerce-laptop
        else
          cd /var/www/ecommerce-laptop
          git remote set-url origin https://github.com/igonoralexander/ecommerce-laptop.git
          git fetch origin main
          git reset --hard origin/main
          git pull origin main --rebase
        fi

        cd /var/www/ecommerce-laptop
        composer install --no-dev --optimize-autoloader
        php artisan config:cache
        php artisan queue:restart
        php artisan optimize
        php artisan migrate --force
        sudo systemctl restart nginx
