name: Deploy Laravel App to VM

on:
  push:
    branches:
      - main  # Runs push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

      - name: Start SSH Agent and Add Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
        run: |
          # Start SSH Agent
          eval "$(ssh-agent -s)" 
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
      
          # Debugging SSH Key Addition
          ssh-add -l || (echo "❌ No SSH key added!" && exit 2)

          # Debug SSH Connection
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} "echo ✅ SSH Connection Successful" || (echo "❌ SSH Connection Failed!" && exit 4)
          
      - name: SSH into VM and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            set -e  # Stop on error
            cd /var/www/photography-website
            git fetch origin main
            git reset --hard origin/main
            git pull origin main --rebase
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan queue:restart
            php artisan optimize
            php artisan migrate
            sudo systemctl restart nginx
          EOF